API/urls.py
from django.urls import path
from . import views

app_name = 'api'

urlpatterns = [
    path('api/users', views.UsersListGenericView.as_view(), name='user-list-generic'),
    path('api/users/<pk>', views.UsersListGenericView.as_view(), name='user-detail-generic'),
    path('api/products', views.ProductListGenericView.as_view(), name='products-list-generic'),
    path('api/products/<pk>', views.ProductDetailGenericView.as_view(), name='products-detail-generic'),
    path('api/blog', views.BlogListGenericView.as_view(), name='blog-list-generic'),
    path('api/blog/<pk>', views.ProductDetailGenericView.as_view(), name='blog-detail-generic'),
    path('api/order', views.OrderListGenericView.as_view(), name='order-list-generic'),
    path('api/order/<pk>', views.OrderDetailGenericView.as_view(), name='order-detail-generic'),
]

home_module/urls.py
from django.urls import path
from . import views

app_name = "home_module"

urlpatterns = [
    path('', views.HomeView.as_view(), name="main"),
    path('about-us', views.AboutUsView.as_view(), name="about-us"),
]

petshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home_module.urls", namespace="home")),
    path("products/", include("product_module.urls", namespace="products")),
    path("account/", include("account_module.urls", namespace="account")),
    path("contact-us/", include("contactus_module.urls", namespace="contact-us")),
    path("blog/", include("blog_module.urls", namespace="blog")),
    path("user/", include("profile_module.urls", namespace="user")),
    path("gallery/", include("gallery_module.urls", namespace="gallery")),
    path('order/', include("order_module.urls", namespace="order")),
    path('panel/', include("admin_panel.urls", namespace="panel")),
    path('', include("API.urls", namespace="api")),
    path('auth-token/', obtain_auth_token, name='generate_auth_token'),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product_module/urls.py
from django.urls import path, include
from . import views
from rest_framework.routers import DefaultRouter

app_name = "products"

urlpatterns = [
    path('', views.ProductView.as_view(), name="products_list"),
    path('<slug:product_id>', views.ProductDetailView.as_view(), name="products_detail"),
    path('cut/<str:category>', views.ProductView.as_view(), name="products_list_category"),

]

product_module/models.py
from django.db import models

from account_module.models import User


class ProductCategory(models.Model):
    title = models.CharField(max_length=250, verbose_name="عنوان")
    url_title = models.SlugField(max_length=250, verbose_name="عنوان در url", null=True)
    is_active = models.BooleanField(verbose_name="فعال / غیرفعال")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'دسته بندی'
        verbose_name_plural = 'دسته بندی ها'


class Product(models.Model):
    name = models.CharField(max_length=250, verbose_name="نام")
    description = models.TextField(verbose_name="توضیحات")
    category = models.ForeignKey(
        ProductCategory,
        on_delete=models.CASCADE,
        null=True, blank=True,
        verbose_name="دسته بندی")

    price = models.IntegerField(verbose_name="قیمت", null=True)
    count = models.IntegerField(verbose_name="تعداد")
    is_active = models.BooleanField(verbose_name="فعال / غیرفعال")
    slug = models.SlugField(verbose_name="اسلاگ", null=False, blank=True, db_index=True)
    image = models.ImageField(upload_to="product_image", verbose_name="عکس محصول", null=True)

    def delete(self, *args, **kwargs):
        storage, path = self.image.storage, self.image.path
        storage.delete(path)
        super().delete(*args, **kwargs)

    def __str__(self) -> str:
        return self.name

    class Meta:
        ordering = ["price"]
        verbose_name = "محصول"
        verbose_name_plural = "محصولات"


class ProductComment(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name="محصول", related_name="comments")
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="کاربر", related_name='users')
    create_date = models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ثبت")
    message = models.TextField(verbose_name="متن نظر")
    response = models.TextField(verbose_name="پاسخ ادمین", null=True, blank=True)
    is_read = models.BooleanField(verbose_name="خوانده شده", default=False)

    def __str__(self):
        return str(self.user)

    class Meta:
        verbose_name = "نظر"
        verbose_name_plural = "نظرات"

product_module/forms.py
from django import forms


class CommentForm(forms.Form):
    message = forms.CharField(widget=forms.Textarea)

product_module/views.py
from django.shortcuts import render
from django.views.generic import ListView, View
from rest_framework.request import Request
from rest_framework.response import Response
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.views import APIView
from rest_framework import generics, mixins
from rest_framework import viewsets

from .models import Product, ProductCategory, ProductComment
from account_module.models import User


class ProductView(ListView):
    template_name = "products.html"
    model = Product
    context_object_name = 'products'
    paginate_by = 6

    def get_queryset(self):
        query = super(ProductView, self).get_queryset()
        category_name = self.kwargs.get('category')
        if category_name is not None:
            query = query.filter(category__url_title__iexact=category_name)
        return query


def product_categories_component(request):
    product_categories: ProductCategory = ProductCategory.objects.filter(is_active=True)[0:3]

    return render(request, 'component/product_categories_component.html', context={
        'categories': product_categories
    })


class ProductDetailView(View):
    def get(self, request, product_id):
        product = Product.objects.filter(is_active=True, id=product_id).first()
        new_product: Product = Product.objects.filter(is_active=True).order_by('price')[0:4]
        comments = product.comments.all().order_by('-create_date')

        comment_message = request.GET.get('message')

        if request.GET:
            new_comment = ProductComment()
            new_comment.message = comment_message
            new_comment.user = request.user
            new_comment.product = product
            if comment_message:
                new_comment.save()

            return render(request, 'comment_product.html', context={
                'product': product,
                'comments': comments,
                'product_new': new_product
            })

        return render(request, 'product_detail.html', context={
            'product': product,
            'comments': comments,
            'product_new': new_product
        })

product_module/templates/comment_product.html
{% load poll_extras %}

{% if comments %}
    <p class="mr-4"> تعداد دیدگاه ها : {{ comments.count }}</p>
{% else %}
    <p class="mr-4">هیچ نظری برای این پست ثبت نشده است</p>
{% endif %}
{# main comment #}
{% if comments %}
    {% for comment in comments %}
        <div class="card p-sm-4 my-4 shadow-lg {% if comment.parent %} mr-4 {% endif %}">
            {{ comment.user }} گفته : {{ comment.message }}
            <br>
            <p style="text-align: left">{{ comment.create_date | jalali }}</p>
        </div>
        {# two level comment #}
        {% if comment.response %}
            <div class="card p-sm-4 my-4 mr-4 shadow-lg">
                <div class="d-flex align-items-center">
                    <div class="ml-2">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16"
                             height="16"
                             fill="green"
                             class="bi bi-patch-check" viewBox="0 0 16 16">
                            <path fill-rule="evenodd"
                                  d="M10.354 6.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L7 8.793l2.646-2.647a.5.5 0 0 1 .708 0z"/>
                            <path d="m10.273 2.513-.921-.944.715-.698.622.637.89-.011a2.89 2.89 0 0 1 2.924 2.924l-.01.89.636.622a2.89 2.89 0 0 1 0 4.134l-.637.622.011.89a2.89 2.89 0 0 1-2.924 2.924l-.89-.01-.622.636a2.89 2.89 0 0 1-4.134 0l-.622-.637-.89.011a2.89 2.89 0 0 1-2.924-2.924l.01-.89-.636-.622a2.89 2.89 0 0 1 0-4.134l.637-.622-.011-.89a2.89 2.89 0 0 1 2.924-2.924l.89.01.622-.636a2.89 2.89 0 0 1 4.134 0l-.715.698a1.89 1.89 0 0 0-2.704 0l-.92.944-1.32-.016a1.89 1.89 0 0 0-1.911 1.912l.016 1.318-.944.921a1.89 1.89 0 0 0 0 2.704l.944.92-.016 1.32a1.89 1.89 0 0 0 1.912 1.911l1.318-.016.921.944a1.89 1.89 0 0 0 2.704 0l.92-.944 1.32.016a1.89 1.89 0 0 0 1.911-1.912l-.016-1.318.944-.921a1.89 1.89 0 0 0 0-2.704l-.944-.92.016-1.32a1.89 1.89 0 0 0-1.912-1.911l-1.318.016z"/>
                        </svg>
                    </div>
                    مدیریت سایت گفته : {{ comment.response }}
                </div>
                <br>
                <p style="text-align: left">{{ comment.create_date | jalali }}</p>
            </div>
        {% endif %}
    {% endfor %}
{% endif %}

product_module/templates/products.html
{% extends "shared/main.html" %}
{% load render_partial %}
{% load poll_extras %}
{% block title %}محصولات{% endblock %}


{% block content %}
    <section class="container-fluid bkg p-0">
        <div class="row">
            <div class="col-lg-12 p-0 mb-3">
                <div class="bg-package d-flex align-items-center justify-content-center">
                    <div class="breadcrumb radius15">
                        <ul class="">
                            <li><a href="{% url "home:main" %}">خانه / </a></li>
                            <li><a href="{% url "products:products_list" %}" class="current">محصولات</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="container mb-4">
        <div class="row">
            <div class="col-xl-3 order-xl-0 pt-3 order-1 mb-3">
                <div class="d-flex align-items-center justify-content-center mb-3 bg-title-sidebar p-2 radius15">
                    <svg width="41" height="41" viewBox="0 0 41 41" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M26.2658 0.97876C28.7008 0.97876 30.6746 4.67863 30.6746 7.81348C30.6746 10.9483 28.7008 13.489 26.2658 13.489C23.8307 13.489 21.8569 10.9479 21.8569 7.81348C21.8569 4.6791 23.8307 0.97876 26.2658 0.97876Z"
                              fill="#FFAA00"/>
                        <path d="M13.7387 0.97876C16.1737 0.97876 18.1475 4.67863 18.1475 7.81348C18.1475 10.9483 16.1737 13.489 13.7387 13.489C11.3036 13.489 9.32983 10.9479 9.32983 7.81348C9.32983 4.6791 11.3036 0.97876 13.7387 0.97876Z"
                              fill="#FFAA00"/>
                        <path d="M0.534818 17.5109C-0.500563 14.9255 -0.0464077 11.2055 2.01777 10.3819C4.08194 9.55835 6.97583 11.9425 8.01027 14.5283C9.04471 17.1142 8.20934 19.8781 6.1447 20.7017C4.08005 21.5252 1.56879 20.0967 0.534818 17.5109Z"
                              fill="#FFAA00"/>
                        <path d="M39.4698 17.5109C38.4344 20.0963 35.9241 21.5253 33.8599 20.7017C31.7957 19.8782 30.9604 17.1142 31.9943 14.5284C33.0283 11.9426 35.9227 9.55745 37.9868 10.3819C40.051 11.2064 40.5037 14.9251 39.4698 17.5109Z"
                              fill="#FFAA00"/>
                        <path d="M35.776 31.7942C35.3054 29.679 34.1759 27.7667 32.9292 25.9965C30.0075 21.85 25.329 17.6627 20.0025 17.6627C14.698 17.6627 9.99787 21.8491 7.07574 25.9965C5.82905 27.7667 4.7019 29.6766 4.22892 31.7942C3.75593 33.9119 4.01478 36.2805 5.3283 37.9991C6.64182 39.7176 9.13097 40.5816 11.0756 39.649C12.2324 39.0953 13.169 37.9789 14.4448 37.8712C15.6167 37.773 16.6521 38.5608 17.6291 39.2198C18.335 39.696 19.1869 40.1294 20.0025 40.135C20.8181 40.1294 21.6694 39.696 22.3758 39.2198C23.3529 38.5617 24.3882 37.773 25.5601 37.8712C26.836 37.9789 27.7721 39.0934 28.9293 39.649C30.874 40.5816 33.3631 39.7214 34.6766 38.001C35.9902 36.2805 36.249 33.9123 35.776 31.7942ZM24.6424 29.2432C24.0414 30.3403 23.0931 31.3063 22.2921 32.0579C21.8629 32.4609 21.4108 32.8388 20.9381 33.1899H20.9353C20.6648 33.3882 20.338 33.4951 20.0025 33.4951C19.6669 33.4951 19.3402 33.3882 19.0697 33.1899H19.0669C18.5941 32.8388 18.142 32.4609 17.7129 32.0579C16.9128 31.3058 15.9635 30.3403 15.3626 29.2432C14.866 28.3374 14.6067 27.3423 14.8637 26.3053C15.1103 25.3116 15.8953 24.4387 16.8582 24.3169C17.9717 24.1759 19.2683 24.9586 20.0025 25.8573C20.7366 24.9586 22.0332 24.1764 23.1467 24.3174C24.1096 24.4392 24.8946 25.3121 25.1413 26.3058C25.3982 27.3423 25.1389 28.3374 24.6424 29.2432Z"
                              fill="#FFAA00"/>
                    </svg>

                    <h3 class="mr-3">دسته بندی</h3>


                </div>

                <div class="card side-category p-4 mb-3">
                    <ul class="list-unstyled">
                        {% render_partial "product_module.views.product_categories_component" %}
                    </ul>
                </div>


                <div class="my-3 text-center">

                    <img src="/static/Img/banner-pet.png" alt="" class="radius30">

                </div>

            </div>

            <div class="col-xl-9 pt-3 order-xl-1 pl-4 order-0 mb-3">
                <div class="row">
                    {% for product in products %}
                        <div class="col-lg-4 col-md-6 mb-4">
                            <div class="card-body mb-3 text-center">
                                <a href="{% url "products:products_detail" product.id %}">
                                    {% if product.image %}
                                    <img class="img-fluid" src="{{ product.image.url }}">
                                    {% endif %}
                                </a>
                                <div>
                                    <h5 class="my-2 YekanBakhFaNum-SemiBold"><a class="card-pro"
                                                                                href="{% url "products:products_detail" product.id %}">{{ product.name }}</a>
                                    </h5>
                                    <span class="color-orange YekanBakhFaNum-Bold fa18">{% if product.count %}
                                        {{ product.price | three_digits }}{% else %}ناموجود{% endif %}</span>
                                    <span class="color-orange YekanBakhFaNum-Regular fa14">{% if product.count %}
                                        تومان{% endif %}</span>
                                    <div class="d-flex justify-content-between align-items-center">
                                        <div class="d-flex">
                                            <div class="add-to-cart hoverable outlined">
                                                <svg width="21" height="22" viewBox="0 0 21 22" fill="none"
                                                     xmlns="http://www.w3.org/2000/svg">
                                                    <path d="M15 21.25C15.9665 21.25 16.75 20.4665 16.75 19.5C16.75 18.5335 15.9665 17.75 15 17.75C14.0335 17.75 13.25 18.5335 13.25 19.5C13.25 20.4665 14.0335 21.25 15 21.25Z"
                                                          fill="#FFAA00"/>
                                                    <path d="M7 21.25C7.9665 21.25 8.75 20.4665 8.75 19.5C8.75 18.5335 7.9665 17.75 7 17.75C6.0335 17.75 5.25 18.5335 5.25 19.5C5.25 20.4665 6.0335 21.25 7 21.25Z"
                                                          fill="#FFAA00"/>
                                                    <path d="M3.59 2.69L3.39 5.14C3.35 5.61 3.72 6 4.19 6H19.5C19.92 6 20.27 5.68 20.3 5.26C20.43 3.49 19.08 2.05 17.31 2.05H5.02C4.92 1.61 4.72 1.19 4.41 0.84C3.91 0.31 3.21 0 2.49 0H0.75C0.34 0 0 0.34 0 0.75C0 1.16 0.34 1.5 0.75 1.5H2.49C2.8 1.5 3.09 1.63 3.3 1.85C3.51 2.08 3.61 2.38 3.59 2.69Z"
                                                          fill="#FFAA00"/>
                                                    <path d="M19.2601 7.5H3.92005C3.50005 7.5 3.16005 7.82 3.12005 8.23L2.76005 12.58C2.62005 14.29 3.96005 15.75 5.67005 15.75H16.7901C18.2901 15.75 19.6101 14.52 19.7201 13.02L20.0501 8.35C20.0901 7.89 19.7301 7.5 19.2601 7.5Z"
                                                          fill="#FFAA00"/>
                                                </svg>
                                                <span class="text-center" onclick="addProductToOrder({{ product.id }})">افزودن به سبد خرید</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}

                </div>
                <div class="row mt-3">
                    <div class="col-12 text-center mx-auto">
                    {% if products %}
                        <ul class="pagination justify-content-center">
                            {% if page_obj.has_previous %}
                                <li class="page-item"><a class="page-link"
                                                         href="?page={{ page_obj.previous_page_number }}">قبلی</a></li>
                            {% endif %}
                            {% for pageNumber in paginator.page_range %}
                                <li class="page-item {% if page_obj.number == pageNumber %} active {% endif %}"><a
                                        class="page-link"
                                        href="?page={{ pageNumber }}">{{ pageNumber }}</a></li>
                            {% endfor %}
                            {% if page_obj.has_next %}
                                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">بعدی</a>
                                </li>
                            {% endif %}
                        </ul>
                    {% endif %}
                    </div>
                </div>


            </div>
        </div>
    </section>
{% endblock %}