API/urls.py
from django.urls import path
from . import views

app_name = 'api'

urlpatterns = [
    path('api/users', views.UsersListGenericView.as_view(), name='user-list-generic'),
    path('api/users/<pk>', views.UsersListGenericView.as_view(), name='user-detail-generic'),
    path('api/products', views.ProductListGenericView.as_view(), name='products-list-generic'),
    path('api/products/<pk>', views.ProductDetailGenericView.as_view(), name='products-detail-generic'),
    path('api/blog', views.BlogListGenericView.as_view(), name='blog-list-generic'),
    path('api/blog/<pk>', views.ProductDetailGenericView.as_view(), name='blog-detail-generic'),
    path('api/order', views.OrderListGenericView.as_view(), name='order-list-generic'),
    path('api/order/<pk>', views.OrderDetailGenericView.as_view(), name='order-detail-generic'),
]

admin_panel/urls.py
from django.urls import path

from . import views

app_name = 'panel'

urlpatterns = [
    path('orders', views.AdminOrderView.as_view(), name='order-admin'),
    path('detail/<pk>', views.AdminOrderDetailView.as_view(), name='order-admin-detail'),
    path('sended/<pk>', views.sended, name='sended'),
    path('cancel/<pk>', views.cancel, name='cancel')
]

petshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home_module.urls", namespace="home")),
    path("products/", include("product_module.urls", namespace="products")),
    path("account/", include("account_module.urls", namespace="account")),
    path("contact-us/", include("contactus_module.urls", namespace="contact-us")),
    path("blog/", include("blog_module.urls", namespace="blog")),
    path("user/", include("profile_module.urls", namespace="user")),
    path("gallery/", include("gallery_module.urls", namespace="gallery")),
    path('order/', include("order_module.urls", namespace="order")),
    path('panel/', include("admin_panel.urls", namespace="panel")),
    path('', include("API.urls", namespace="api")),
    path('auth-token/', obtain_auth_token, name='generate_auth_token'),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin_panel/models.py
from django.db import models

# Create your models here.

admin_panel/views.py
from django.shortcuts import render, redirect
from django.views import View

from order_module.models import Order, OrderCheckout, OrderDetail


class AdminOrderView(View):
    def get(self, request):
        orders = OrderCheckout.objects.select_related('order').select_related("user")
        return render(request, 'order-admin.html', context={
            'orders': orders,
        })


class AdminOrderDetailView(View):
    def get(self, request, pk):
        products = OrderDetail.objects.filter(order_id=pk).all()
        return render(request, 'checkout-admin.html', context={
            'products': products
        })


def sended(request, pk):
    obj: OrderCheckout = OrderCheckout.objects.get(order_id=pk)
    obj.sended = True
    obj.save()

    return redirect('panel:order-admin')


def cancel(request, pk):
    obj: OrderCheckout = OrderCheckout.objects.get(order_id=pk)
    obj.sended = False
    obj.save()

    return redirect('panel:order-admin')

admin_panel/templates/checkout-admin.html
{% extends 'shared/main.html' %}
{% block title %}{% endblock %}


{% block content %}
    {% if request.user.is_superuser %}
        <div class="m-5">
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th scope="col">نام محصول</th>
                    <th scope="col">قیمت واحد</th>
                    <th scope="col">تعداد</th>
                    <th scope="col">جمع کل</th>
                </tr>
                </thead>
                <tbody>
                {% for item in products %}
                    <tr>
                        <th scope="row">{{ item.product.name }}</th>
                        <td>{{ item.product.price }}</td>
                        <td>{{ item.count }}</td>
                        <td>{{ item.get_total_price }}</td>
                    </tr>
                    </tbody>
                {% endfor %}
            </table>
        </div>
        <a href="{% url 'panel:sended' products.first.order %}"
           class="btn bg-success w-25 text-white rounded-left rounded-right mx-auto mx-4 my-2 d-block">تایید ارسال</a>
        <a href="{% url 'panel:cancel' products.first.order %}"
           class="btn bg-danger w-25 text-white rounded-left rounded-right mx-auto mx-4 my-2 d-block">کنسل کردن
            ارسال</a>
    {% else %}
        <h1 class="text-center my-5">ظاهرا شما گم شدید :)</h1>
    {% endif %}
{% endblock %}

admin_panel/templates/order-admin.html
{% extends 'shared/main.html' %}
{% block title %}{% endblock %}

{% block content %}
    {% if request.user.is_superuser %}
        <div class="m-5">
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th scope="col">شماره سفارش</th>
                    <th scope="col">نام</th>
                    <th scope="col">نام خانوادگی</th>
                    <th scope="col">شماره تماس</th>
                    <th scope="col">آدرس</th>
                    <th scope="col">وضعیت پرداخت</th>
                    <th scope="col">وضعیت ارسال</th>
                    <th>مشاهده جزئیات</th>
                </tr>
                </thead>
                {% for item in orders %}
                    <tbody>
                    <tr>
                        <th scope="row">{{ item.order.id }}</th>
                        <td>{{ item.user.first_name }}</td>
                        <td>{{ item.user.last_name }}</td>
                        <td>{{ item.user.phone_number }}</td>
                        <td>{{ item.state }}, {{ item.city }}, {{ item.street }}, {{ item.apartment }}, {{ item.zipcode }}</td>
                        <td class="text-white {% if item.order.is_paid == True %} bg-success {% else %} bg-danger {% endif %}">
                            {% if item.order.is_paid == True %}
                                پرداخت شده
                            {% else %}
                                پرداخت نشده
                            {% endif %}
                        </td>
                        <td class="text-white {% if item.sended == True %} bg-success {% else %} bg-danger {% endif %}">
                            {% if item.sended == True %}
                                ارسال شده
                            {% else %}
                                ارسال نشده
                            {% endif %}
                        </td>
                        <td class="text-center"><a href="{% url "panel:order-admin-detail" item.order.id %}"
                                                   class="text-dark"><i
                                class="fas fa-eye"></i></a></td>
                    </tr>
                    </tbody>
                {% endfor %}
            </table>
        </div>
    {% else %}
        <h1 class="text-center my-5">ظاهرا شما گم شدید :)</h1>
    {% endif %}
{% endblock %}