API/urls.py
from django.urls import path
from . import views

app_name = 'api'

urlpatterns = [
    path('api/users', views.UsersListGenericView.as_view(), name='user-list-generic'),
    path('api/users/<pk>', views.UsersListGenericView.as_view(), name='user-detail-generic'),
    path('api/products', views.ProductListGenericView.as_view(), name='products-list-generic'),
    path('api/products/<pk>', views.ProductDetailGenericView.as_view(), name='products-detail-generic'),
    path('api/blog', views.BlogListGenericView.as_view(), name='blog-list-generic'),
    path('api/blog/<pk>', views.ProductDetailGenericView.as_view(), name='blog-detail-generic'),
    path('api/order', views.OrderListGenericView.as_view(), name='order-list-generic'),
    path('api/order/<pk>', views.OrderDetailGenericView.as_view(), name='order-detail-generic'),
]

order_module/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('add-to-order', views.add_product_to_order, name='add_to_order'),
    path('checkout', views.CheckOutView.as_view(), name='checkout'),
    path('request', views.request_payment, name='request_payment'),
    path('verify', views.verify_payment, name='verify_payment'),
    path('seccess', views.secces_payment_redirect, name='secces_payment_redirect'),
    path('unseccess', views.unsecces_payment_redirect, name='unsecces_payment_redirect')
]

petshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home_module.urls", namespace="home")),
    path("products/", include("product_module.urls", namespace="products")),
    path("account/", include("account_module.urls", namespace="account")),
    path("contact-us/", include("contactus_module.urls", namespace="contact-us")),
    path("blog/", include("blog_module.urls", namespace="blog")),
    path("user/", include("profile_module.urls", namespace="user")),
    path("gallery/", include("gallery_module.urls", namespace="gallery")),
    path('order/', include("order_module.urls", namespace="order")),
    path('panel/', include("admin_panel.urls", namespace="panel")),
    path('', include("API.urls", namespace="api")),
    path('auth-token/', obtain_auth_token, name='generate_auth_token'),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profile_module/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('dashboard', views.UserProfileView.as_view(), name='dashboard'),
    path('edit', views.UserEditProfile.as_view(), name='edit_profile'),
    path('change-passoword', views.ChangePasswordView.as_view(), name='change_password'),
    path('cart', views.user_basket, name='cart'),
    path('delete-order-detail', views.delete_order_datail_func, name='delete_order_detail_ajax'),
    path('change-order-detail', views.change_order_datail_count, name='change_order_detail_count'),
    path('last-order-detail', views.last_order_detail, name='last_order_detail'),
]

profile_module/models.py
from django.db import models

profile_module/forms.py
from django import forms
from account_module.models import User


class EditeProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'address', 'phone_number', 'profile_image']


class ChangePasswordForm(forms.Form):
    old_password = forms.CharField(
        label="رمز عبور فعلی",
        widget=forms.TextInput(),
        error_messages={
            'required': 'رمزعبور خود را وارد کنید'
        }
    )
    new_password = forms.CharField(
        label="رمز عبور جدید",
        widget=forms.TextInput(),
        error_messages={
            'required': 'رمزعبور خود را مجددا وارد کنید'
        }
    )
    confirm_password = forms.CharField(
        label="تایید رمز عبور ",
        widget=forms.TextInput(),
        error_messages={
            'required': 'رمزعبور خود را مجددا وارد کنید'
        }
    )

    def clean_confirm_password(self):
        password = self.cleaned_data.get('new_password')
        confirm_password = self.cleaned_data.get('confirm_password')

        if password == confirm_password:
            return confirm_password
        else:
            raise forms.ValidationError("رمز عبور های وارد شده یکسان نیستند")

profile_module/views.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.urls import reverse
from django.views import View
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

from account_module.models import User
from order_module.models import Order, OrderDetail, OrderCheckout
from .forms import EditeProfileForm, ChangePasswordForm


class UserProfileView(View):
    def get(self, request):
        return render(request, 'user_profile.html', context={

        })


class UserEditProfile(View):

    def get(self, request):
        current_user = User.objects.filter(id=request.user.id).first()
        edit_form: EditeProfileForm = EditeProfileForm(instance=current_user)

        return render(request, "edite_profile.html", context={
            'edit_form': edit_form,
            'user': current_user
        })

    def post(self, request):
        current_user = User.objects.filter(id=request.user.id).first()
        edit_form: EditeProfileForm = EditeProfileForm(request.POST, request.FILES, instance=current_user)
        if edit_form.is_valid():
            edit_form.save(commit=True)
            return redirect('user:edit_profile')
        return render(request, "edite_profile.html", context={
            'edit_form': edit_form,
        })


class ChangePasswordView(LoginRequiredMixin, View):
    login_url = "/account/login"

    def get(self, request):
        change_password: ChangePasswordForm = ChangePasswordForm()
        return render(request, "change_password.html", context={
            'change_password': change_password
        })

    def post(self, request):
        change_password: ChangePasswordForm = ChangePasswordForm(request.POST)
        if change_password.is_valid():
            user = User.objects.filter(id=request.user.id).first()
            is_correct_password = user.check_password(change_password.cleaned_data.get('old_password'))

            if is_correct_password:
                user.set_password(change_password.cleaned_data.get('confirm_password'))
                user.save()
                return redirect('account:login')
            else:
                change_password.add_error('old_password', 'رمزعبور فعلی اشتباه میباشد')
        else:
            change_password.add_error('new_password', 'خطایی در تغییر رمز عبور پیش آمده است')

        return render(request, "change_password.html", context={
            'change_password': change_password
        })


def profile_menu(request):
    return render(request, "components/profile_menu.html", context={

    })


@login_required(login_url="/account/login")
def user_basket(request):
    current_order, created = Order.objects.prefetch_related('orderdetail_set').get_or_create(user_id=request.user.id,
                                                                                             is_paid=False)
    total_amoutn = 0

    for order_detail in current_order.orderdetail_set.all():
        total_amoutn += order_detail.product.price * order_detail.count

    return render(request, "user_basket.html", context={
        'order': current_order,
        'sum': total_amoutn
    })


def delete_order_datail_func(request):
    detail_id = request.GET.get('detail_id')

    if detail_id is None:
        return JsonResponse({
            'status': 'not found detail id'
        })

    current_order, created = Order.objects.prefetch_related('orderdetail_set').get_or_create(
        user_id=request.user.id, is_paid=False)
    detail = current_order.orderdetail_set.filter(id=detail_id).first()

    if detail is None:
        return JsonResponse({
            'status': 'detail not found'
        })
    detail.delete()

    current_order, created = Order.objects.prefetch_related('orderdetail_set').get_or_create(
        user_id=request.user.id, is_paid=False)
    total_amoutn = 0
    for order_detail in current_order.orderdetail_set.all():
        total_amoutn += order_detail.product.price * order_detail.count

    context = {
        'order': current_order,
        'sum': total_amoutn
    }
    data = render_to_string('basket_content.html', context)
    return JsonResponse({
        'status': 'success',
        'body': data
    })


def change_order_datail_count(request):
    detail_id = request.GET.get('detail_id')
    state = request.GET.get('state')

    if detail_id is None or state is None:
        return JsonResponse({
            'status': 'not_found_detail_id_or_state'
        })

    order_detail = OrderDetail.objects.filter(id=detail_id, order__user_id=request.user.id,
                                              order__is_paid=False).first()
    if order_detail is None:
        return JsonResponse({
            'status': 'detail_not_found'
        })

    if state == 'increase':
        order_detail.count += 1
        order_detail.save()


    elif state == 'decrease':
        if order_detail.count == 1:
            order_detail.delete()


        else:
            order_detail.count -= 1
            order_detail.save()


    else:
        return JsonResponse({
            'status': 'state invalid'
        })

    current_order, created = Order.objects.prefetch_related('orderdetail_set').get_or_create(
        user_id=request.user.id, is_paid=False)
    total_amoutn = current_order.calculate_total_price()

    context = {
        'order': current_order,
        'sum': total_amoutn
    }

    return JsonResponse({
        'status': 'success',
        'body': render_to_string('basket_content.html', context)
    })


@login_required(login_url="/account/login")
def last_order_detail(request):
    last_order: OrderCheckout = OrderCheckout.objects.select_related('order').select_related('user').filter(order__user_id=request.user.id, order__is_paid=True)
    return render(request, 'last_order.html', context={
        'last_order': last_order,
    })

profile_module/templates/basket_content.html
{% load poll_extras %}

<section class="container mb-4" id="carts">
    <div class="row">
        <div class="col-xl-4 order-xl-1 pt-3 order-1 mb-3">

            <div class="card side-category p-4 mb-3">
                <ul class="list-unstyled">

                    <li class="p-3 bg-title-sidebar radius15">مجموع سبد خرید:

                        <div class="d-flex align-items-center justify-content-center">
                            {{ sum | three_digits }} تومان
                        </div>

                    </li>
                </ul>
                <li>
                    هزینه این سفارش هنوز پرداخـت نشده و در صورت اتمــام موجــودی
                    کالا ها از سبد خرید شما حدف می شوند.
                </li>
                {% if order.orderdetail_set.all %}
                    <a class="a-button radius55 py-3 px-4 text-center mt-3" href="{% url 'order:checkout' %}">
                        <span class="ml-2">ثبت سفارش و پرداخت</span>
                    </a>
                {% else %}

                {% endif %}
            </div>
        </div>

        <div class="col-xl-8 order-xl-0 order-0 mb-3">

            <div class="card m-3 p-4">
                {% if order.orderdetail_set.all %}
                    <div class="item">
                        {% for item in order.orderdetail_set.all %}
                            <div class="d-flex align-items-center justify-content-between mb-cart cart-res"
                                 id="items">
                                <div class="col-lg-3">
                                    <img src="{{ item.product.image.url }}" alt="">
                                </div>
                                <div class="col-lg-3">{{ item.product.name }}</div>
                                <div class="col-lg-3">{{ item.get_total_price | three_digits }} تومان</div>
                                <div class="col-lg-3">
                                    <div class="input-group d-flex align-items-center justify-content-center cart-increment radius20">

                                                    <span class="input-group-btn">
                                                        <button type="button"
                                                                onclick="changeOrderDetialCount({{ item.id }}, 'increase')"
                                                                class="quantity-right-plus btn "
                                                                data-type="plus" data-field="">
                                                            <i class="fas fa-plus text-warning"></i>
                                                        </button>
                                                    </span>

                                        <input type="text" id="quantity" name="quantity"
                                               class="input-cart form-control input-number" value="{{ item.count }}"
                                               min="1"
                                               max="100">

                                        <span class="input-group-btn">
                                                        <button type="button"
                                                                onclick="changeOrderDetialCount({{ item.id }}, 'decrease')"
                                                                class="quantity-left-minus btn p-3"
                                                                data-type="minus" data-field="">
                                                            <i class="fas fa-minus text-warning"></i>
                                                        </button>
                                                    </span>

                                    </div>
                                    <button onclick="removeOrderDetail({{ item.id }})"
                                            class="btn bg-danger text-white mx-auto d-block my-2 d-flex justify-content-center align-items-center rounded-left rounded-right">
                                        <i class="fas fa-trash"></i>
                                    </button>
                                </div>

                            </div>
                        {% endfor %}

                    </div>
                {% else %}
                    <h4 class="text-center text-muted ">سبد خرید شما خالی میباشد</h4>
                {% endif %}
            </div>

        </div>

    </div>

</section>

profile_module/templates/change_password.html
{% extends "shared/main.html" %}
{% load render_partial %}
{% block title %}تغییر رمزعبور{% endblock %}


{% block content %}
    <div class="container d-md-flex align-items-start justify-content-between">
        <div class="mx-auto bg-white mt-1 mb-3 rounded-top p-5">
            <h4>تغییر رمزعبور</h4>
            <form method="post" action="{% url 'user:change_password' %}" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group mt-3 d-flex flex-column list-group">
                    <input type="password" name="old_password" class="list-group-item" placeholder="رمزعبور فعلی">
                    <span class="">{{ change_password.old_password.errors }}</span>
                    <input type="password" name="new_password" class="list-group-item" placeholder="رمزعبور جدید">
                    <span class="">{{ change_password.new_password.errors }}</span>
                    <input type="password" name="confirm_password" class="list-group-item"
                           placeholder="تکرار رمزعبور جدید">
                    <span class="">{{ change_password.confirm_password.errors }}</span>
                    <button type="submit" class="btn bg-success text-center text-white my-3">تایید</button>
                </div>
            </form>
        </div>
        {% render_partial 'profile_module.views.profile_menu' %}
    </div>

{% endblock %}

profile_module/templates/edite_profile.html
{% extends "shared/main.html" %}
{% load render_partial %}
{% block title %}ویرایش پروفایل{% endblock %}

{% block content %}
    <div class="container d-md-flex align-items-start justify-content-between">
        <div class="mx-auto bg-white mt-1 mb-3 rounded-top px-5">
            <img src="{{ user.profile_image.url }}" class="d-block my-3 rounded-circle mx-auto">
            <form method="post" action="{% url 'user:edit_profile' %}" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group mt-3 d-flex flex-column list-group">
                    <label>نام</label>
                    <input type="text" name="first_name" class="list-group-item" value="{{ user.first_name }}">
                    <label>نام خانوادگی</label>
                    <input type="text" name="last_name" class="list-group-item" value="{{ user.last_name }}">
                    <label>شماره تلفن</label>
                    <input type="text" name="phone_number" class="list-group-item" value="{{ user.phone_number }}">
                    <label>آدرس</label>
                    <textarea name="address" class="list-group-item">{{ user.address }}</textarea>
                    <label>تصویر پروفایل</label>
                    <input type="file" class="my-3" name="profile_image">
                    <button type="submit" class="btn bg-warning w-25 my-3">ویرایش</button>
                </div>
            </form>
        </div>
        {% render_partial 'profile_module.views.profile_menu' %}
    </div>
{% endblock %}

profile_module/templates/last_order.html
{% extends 'shared/main.html' %}
{% load render_partial %}
{% block title %}آخرین سفارشات{% endblock %}

{% block content %}
    {#         <div class="m-3">#}
    {#            <table class="table table-bordered">#}
    {#                <thead>#}
    {#                <tr>#}
    {#                    <th scope="col">شماره سفارش</th>#}
    {#                    <th scope="col">وضعیت پرداخت</th>#}
    {#                </tr>#}
    {#                </thead>#}
    {#                {% for item in last_order.order %}#}
    {#                    <tbody>#}
    {#                    <tr>#}
    {#                        <th scope="row">{{ item.id }}</th>#}
    {#                    </tr>#}
    {#                    </tbody>#}
    {#                {% endfor %}#}
    {#            </table>#}
    {#        </div>#}
    {#        </div>#}
    {#    <div class="d-flex justify-content-center">#}
    {#    <a class="btn bg-danger text-white text-center my-3 " href="{% url 'user:dashboard' %}">بازگشت</a>#}
    {#    </div>#}
    <div class="m-5">
        <table class="table table-bordered">
            <thead>
            <tr>
                <th scope="col">شماره سفارش</th>
                <th scope="col">نام</th>
                <th scope="col">نام خانوادگی</th>
                <th scope="col">شماره تماس</th>
                <th scope="col">آدرس</th>
                <th scope="col">وضعیت ارسال</th>
            </tr>
            </thead>
            {% for item in last_order %}
                <tbody>
                <tr>
                    <th scope="row">{{ item.order.id }}</th>
                    <td>{{ item.user.first_name }}</td>
                    <td>{{ item.user.last_name }}</td>
                    <td>{{ item.user.phone_number }}</td>
                    <td>{{ item.state }}, {{ item.city }}, {{ item.street }}, {{ item.apartment }}, {{ item.zipcode }}</td>

                    <td class="text-white {% if item.sended == True %} bg-success {% else %} bg-danger {% endif %}">
                        {% if item.sended == True %}
                            ارسال شده
                        {% else %}
                            ارسال نشده
                        {% endif %}
                    </td>

                </tr>
                </tbody>
            {% endfor %}
        </table>
    </div>
{% endblock %}

profile_module/templates/user_basket.html
{% extends 'shared/main.html' %}
{% load poll_extras %}
{% block title %}سبد خرید{% endblock %}


{% block content %}

    <div class="clearfix"></div>

    <section class="container-fluid bkg p-0">
        <div class="row">
            <div class="col-lg-12 p-0 mb-3">
                <div class="bg-package d-flex align-items-center justify-content-center">
                    <div class="breadcrumb radius15">
                        <ul class="">
                            <li><a href="#">خانه / </a></li>
                            <li><a href="#" class="current">سبد خرید</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <div id="order-detail-content">
        <section class="container mb-4" id="carts">
            <div class="row">
                <div class="col-xl-4 order-xl-1 pt-3 order-1 mb-3">

                    <div class="card side-category p-4 mb-3">
                        <ul class="list-unstyled">

                            <li class="p-3 bg-title-sidebar radius15">مجموع سبد خرید:

                                <div class="d-flex align-items-center justify-content-center">
                                    {{ sum | three_digits }} تومان
                                </div>

                            </li>
                        </ul>
                        <li>
                            هزینه این سفارش هنوز پرداخـت نشده و در صورت اتمــام موجــودی
                            کالا ها از سبد خرید شما حدف می شوند.
                        </li>
                        {% if order.orderdetail_set.all %}
                            <a class="a-button radius55 py-3 px-4 text-center mt-3" href="{% url 'order:checkout' %}">
                                <span class="ml-2">ثبت سفارش و پرداخت</span>
                            </a>
                        {% else %}

                        {% endif %}
                    </div>
                </div>

                <div class="col-xl-8 order-xl-0 order-0 mb-3">

                    <div class="card m-3 p-4">
                        {% if order.orderdetail_set.all %}
                            <div class="item">
                                {% for item in order.orderdetail_set.all %}
                                    <div class="d-flex align-items-center justify-content-between mb-cart cart-res"
                                         id="items">
                                        <div class="col-lg-3">
                                            <img src="{{ item.product.image.url }}" alt="">
                                        </div>
                                        <div class="col-lg-3">{{ item.product.name }}</div>
                                        <div class="col-lg-3">{{ item.get_total_price | three_digits }} تومان</div>
                                        <div class="col-lg-3">
                                            <div class="input-group d-flex align-items-center justify-content-center cart-increment radius20">

                                                    <span class="input-group-btn">
                                                        <button type="button"
                                                                onclick="changeOrderDetialCount({{ item.id }}, 'increase')"
                                                                class="quantity-right-plus btn "
                                                                data-type="plus" data-field="">
                                                            <i class="fas fa-plus text-warning"></i>
                                                        </button>
                                                    </span>

                                                <input type="text" id="quantity" name="quantity"
                                                       class="input-cart form-control input-number"
                                                       value="{{ item.count }}"
                                                       min="1"
                                                       max="100">

                                                <span class="input-group-btn">
                                                        <button type="button"
                                                                onclick="changeOrderDetialCount({{ item.id }}, 'decrease')"
                                                                class="quantity-left-minus btn p-3"
                                                                data-type="minus" data-field="">
                                                            <i class="fas fa-minus text-warning"></i>
                                                        </button>
                                                    </span>

                                            </div>
                                            <button onclick="removeOrderDetail({{ item.id }})"
                                                    class="btn bg-danger text-white mx-auto d-block my-2 d-flex justify-content-center align-items-center rounded-left rounded-right">
                                                <i class="fas fa-trash"></i>
                                            </button>
                                        </div>

                                    </div>
                                {% endfor %}

                            </div>
                        {% else %}
                            <h4 class="text-center text-muted ">سبد خرید شما خالی میباشد</h4>
                        {% endif %}
                    </div>

                </div>

            </div>

        </section>
    </div>

{% endblock %}