API/urls.py
from django.urls import path
from . import views

app_name = 'api'

urlpatterns = [
    path('api/users', views.UsersListGenericView.as_view(), name='user-list-generic'),
    path('api/users/<pk>', views.UsersListGenericView.as_view(), name='user-detail-generic'),
    path('api/products', views.ProductListGenericView.as_view(), name='products-list-generic'),
    path('api/products/<pk>', views.ProductDetailGenericView.as_view(), name='products-detail-generic'),
    path('api/blog', views.BlogListGenericView.as_view(), name='blog-list-generic'),
    path('api/blog/<pk>', views.ProductDetailGenericView.as_view(), name='blog-detail-generic'),
    path('api/order', views.OrderListGenericView.as_view(), name='order-list-generic'),
    path('api/order/<pk>', views.OrderDetailGenericView.as_view(), name='order-detail-generic'),
]

account_module/urls.py
from django.urls import path
from . import views

app_name = "account"

urlpatterns = [
    path("signup", views.RegisterView.as_view(), name="signup"),
    path("login", views.LoginView.as_view(), name="login"),
    path("logout", views.LogOutView.as_view(), name="log_out"),
    path('activate-account/<email_active_code>', views.ActivateAccountView.as_view(), name="activate_account"),
    path("forget-password", views.ForgetPasswordView.as_view(), name="forget-password"),
    path("reset-password/<active_code>", views.ResetPasswordView.as_view(), name="reset-password"),
]

petshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home_module.urls", namespace="home")),
    path("products/", include("product_module.urls", namespace="products")),
    path("account/", include("account_module.urls", namespace="account")),
    path("contact-us/", include("contactus_module.urls", namespace="contact-us")),
    path("blog/", include("blog_module.urls", namespace="blog")),
    path("user/", include("profile_module.urls", namespace="user")),
    path("gallery/", include("gallery_module.urls", namespace="gallery")),
    path('order/', include("order_module.urls", namespace="order")),
    path('panel/', include("admin_panel.urls", namespace="panel")),
    path('', include("API.urls", namespace="api")),
    path('auth-token/', obtain_auth_token, name='generate_auth_token'),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account_module/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django_resized import ResizedImageField


class User(AbstractUser):
    phone_number = models.CharField(max_length=11, verbose_name="تلفن همراه")
    email_active_code = models.CharField(max_length=100, verbose_name="کد فعالسازی")
    address = models.CharField(max_length=250, verbose_name="آدرس", default="ثبت نشده", blank=True)
    profile_image = ResizedImageField(upload_to="user_profile", size=[80 , 80], crop=['middle', 'center'],quality=100, blank=True)
    order_count =  models.IntegerField(null=True, default=0 ,verbose_name='تعداد خرید')
    total_buy = models.IntegerField(null=True, default=0, verbose_name='مجموع خرید')

    def delete(self, *args, **kwargs):
            storage, path = self.image.storage, self.image.path
            storage.delete(path)
            super().delete(*args, **kwargs)

    class Meta:
        verbose_name = "کاربر"
        verbose_name_plural="کاربران"

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

account_module/forms.py
from django import forms

from account_module.models import User


class RegisterForm(forms.Form):
    first_name = forms.CharField(
        label="نام",
        widget=forms.TextInput()
    )
    last_name = forms.CharField(
        label="نام خانوادگی",
        widget=forms.TextInput()
    )
    phone_number = forms.IntegerField(
        label="شماره تماس",
        widget=forms.NumberInput()
    )
    email = forms.EmailField(
        label="ایمیل",
        widget=forms.EmailInput()
    )
    password = forms.CharField(
        label="پسورد",
        widget=forms.TextInput()
    )
    confirm_password = forms.CharField(
        label="تکرار پسورد",
        widget=forms.TextInput()
    )

    def clean_confirm_password(self):
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')

        if password == confirm_password:
            return confirm_password
        else:
            raise forms.ValidationError("رمز عبور های وارد شده یکسان نیستند")

    def clean_email(self):
        email = self.cleaned_data['email']
        check = User.objects.filter(email=email).exists()
        if check:
            raise forms.ValidationError("email is already in use")
        return email


class LoginForm(forms.Form):
    email = forms.EmailField(
        label="ایمیل",
        widget=forms.EmailInput(),
        error_messages={
            'required': 'ایمیل خود را وارد کنید'
        }
    )

    password = forms.CharField(
        label="پسورد",
        widget=forms.TextInput(),
        error_messages={
            'required': 'رمزعبور خود را وارد کنید'
        }
    )


class ForgetPasswordForm(forms.Form):
    email = forms.EmailField(
        label="ایمیل",
        widget=forms.EmailInput(),
        error_messages={
            'required': 'ایمیل خود را وارد کنید'
        }
    )

class ResetPasswordForm(forms.Form):
    password = forms.CharField(
        label="پسورد",
        widget=forms.TextInput(),
        error_messages={
            'required': 'رمزعبور خود را وارد کنید'
        }
    )
    confirm_password = forms.CharField(
        label="تایید پسورد",
        widget=forms.TextInput(),
        error_messages={
            'required': 'رمزعبور خود را مجددا وارد کنید'
        }
    )

account_module/views.py
from django.contrib.auth import login, logout
from django.http import HttpResponse, Http404
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils.crypto import get_random_string
from django.views import View
from django.views.generic import TemplateView

from utils.email_service import send_email
from .forms import RegisterForm, LoginForm, ForgetPasswordForm, ResetPasswordForm
from .models import User


class RegisterView(TemplateView):
    def get(self, request):
        form = RegisterForm()
        return render(request, 'signup.html', context={
            'form': form
        })

    def post(self, request):
        form = RegisterForm(request.POST)
        if form.is_valid():
            exist_user: User & bool = User.objects.filter(email__iexact=form.cleaned_data.get('email')).exists()
            if not exist_user:
                new_user = User()
                new_user.first_name = form.cleaned_data.get('first_name')
                new_user.last_name = form.cleaned_data.get('last_name')
                new_user.email = form.cleaned_data.get('email')
                new_user.phone_number = form.cleaned_data.get('phone_number')
                new_user.username = form.cleaned_data.get('phone_number')
                new_user.set_password(form.cleaned_data.get('password'))
                new_user.email_active_code = get_random_string(72)
                new_user.is_active = False
                new_user.is_staff = False
                new_user.is_superuser = False
                new_user.save()
                send_email('فعالسازی حساب', new_user.email, {'user': new_user}, 'emails/active_account.html')
                return redirect("home:main")
            else:
                form.add_error('email', 'این ایمیل از قبل ثبت شده است')
        else:
            form.add_error('email', 'خطایی در ثبت نام رخ داده است')
        return render(request, 'signup.html', context={
            'form': form
        })


class ActivateAccountView(View):
    def get(self, request, email_active_code):
        user = User.objects.filter(email_active_code__iexact=email_active_code).first()
        if user is not None:
            if not user.is_active:
                user.is_active = True
                user.email_active_code = get_random_string(72)
                user.save()
                return redirect(reverse('home:main'))
            else:
                HttpResponse("your account is activated")
        raise Http404


class LoginView(View):
    def get(self, request):
        form = LoginForm()
        return render(request, 'login.html', context={
            'form': form
        })

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            user: User = User.objects.filter(email__iexact=form.cleaned_data.get('email')).first()
            if user is not None:
                if not user.is_active:
                    form.add_error('email', 'حساب کاربری شما فعال نشده است، لطفا با پشتیبانی در تماس باشید')
                else:
                    is_password_correct = user.check_password(form.cleaned_data.get('password'))
                    if is_password_correct:
                        login(request, user)
                        return redirect(reverse("user:dashboard"))
                    else:
                        form.add_error('email', 'ایمیل یا پسورد اشتباه است')
            else:
                form.add_error('email', 'لطفا ابتدا ثبت نام کنید')
        else:
            form.add_error('email', 'خطایی هنگام ورود رخ داد')

        return render(request, 'login.html', context={
            'form': form,
        })


class LogOutView(View):
    def get(self, request):
        logout(request)
        return redirect("home:main")


class ForgetPasswordView(View):
    def get(self, request):
        form = ForgetPasswordForm()
        return render(request, "forget-password.html", context={
            'form': form
        })

    def post(self, request):
        form = ForgetPasswordForm(request.POST)
        if form.is_valid():
            user = User.objects.filter(email__iexact=form.cleaned_data.get('email')).first()
            if user is not None:
                if user.is_active:
                    send_email('بازیابی رمز عبور', user.email, {'user': user}, 'emails/reset_password.html')
                    return redirect('account:login')
                else:
                    form.add_error('email', 'حساب کاربری فعال نشده')
            else:
                form.add_error('email',
                               'همچین کاربری یافت نشد... دوباره امتحان کنید یا در سایت لاگین کنید')
        else:
            form.add_error('email', 'خطایی در تکمیل فرم رخ داده')

        return render(request, "forget-password.html", context={
            'form': form
        })


class ResetPasswordView(View):
    def get(self, request, active_code):
        user = User.objects.filter(email_active_code__iexact=active_code).first()
        if user is None:
            return redirect(reverse('account:login'))
        else:
            form = ResetPasswordForm()
        return render(request, "reset-password.html", context={
            'form': form,
            'user': user
        })

    def post(self, request, active_code):
        form = ResetPasswordForm(request.POST)
        if form.is_valid():
            user = User.objects.filter(email_active_code__iexact=active_code).first()
            if user is None:
                return redirect(reverse('account:login'))

            user.set_password(form.cleaned_data.get('password'))
            user.email_active_code = get_random_string(72)
            user.is_active = True
            user.save()
            return redirect(reverse('account:login'))
        else:
            raise Http404

        return render(request, "reset-password.html", context={
            'form': form,
            'user': user
        })

account_module/templates/forget-password.html
{% extends "shared/main.html" %}
{% block title %}بازیابی رمزعبور{% endblock %}



{% block content %}
    <section class="container-fluid text-lg-right text-center mt-4 p-3 mb-5">
        <div class="container">

            <div class="row d-flex align-items-center pt-lg-5">

                <div class="col-lg-7 pl-lg-5 text-center order-2 order-lg-1">
                    <div class="d-flex align-items-center mb-3">
                        <svg width="41" height="41" viewBox="0 0 41 41" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M26.2658 0.97876C28.7008 0.97876 30.6746 4.67863 30.6746 7.81348C30.6746 10.9483 28.7008 13.489 26.2658 13.489C23.8307 13.489 21.8569 10.9479 21.8569 7.81348C21.8569 4.6791 23.8307 0.97876 26.2658 0.97876Z"
                                  fill="#FFAA00"/>
                            <path d="M13.7387 0.97876C16.1737 0.97876 18.1475 4.67863 18.1475 7.81348C18.1475 10.9483 16.1737 13.489 13.7387 13.489C11.3036 13.489 9.32983 10.9479 9.32983 7.81348C9.32983 4.6791 11.3036 0.97876 13.7387 0.97876Z"
                                  fill="#FFAA00"/>
                            <path d="M0.534818 17.5109C-0.500563 14.9255 -0.0464077 11.2055 2.01777 10.3819C4.08194 9.55835 6.97583 11.9425 8.01027 14.5283C9.04471 17.1142 8.20934 19.8781 6.1447 20.7017C4.08005 21.5252 1.56879 20.0967 0.534818 17.5109Z"
                                  fill="#FFAA00"/>
                            <path d="M39.4698 17.5109C38.4344 20.0963 35.9241 21.5253 33.8599 20.7017C31.7957 19.8782 30.9604 17.1142 31.9943 14.5284C33.0283 11.9426 35.9227 9.55745 37.9868 10.3819C40.051 11.2064 40.5037 14.9251 39.4698 17.5109Z"
                                  fill="#FFAA00"/>
                            <path d="M35.776 31.7942C35.3054 29.679 34.1759 27.7667 32.9292 25.9965C30.0075 21.85 25.329 17.6627 20.0025 17.6627C14.698 17.6627 9.99787 21.8491 7.07574 25.9965C5.82905 27.7667 4.7019 29.6766 4.22892 31.7942C3.75593 33.9119 4.01478 36.2805 5.3283 37.9991C6.64182 39.7176 9.13097 40.5816 11.0756 39.649C12.2324 39.0953 13.169 37.9789 14.4448 37.8712C15.6167 37.773 16.6521 38.5608 17.6291 39.2198C18.335 39.696 19.1869 40.1294 20.0025 40.135C20.8181 40.1294 21.6694 39.696 22.3758 39.2198C23.3529 38.5617 24.3882 37.773 25.5601 37.8712C26.836 37.9789 27.7721 39.0934 28.9293 39.649C30.874 40.5816 33.3631 39.7214 34.6766 38.001C35.9902 36.2805 36.249 33.9123 35.776 31.7942ZM24.6424 29.2432C24.0414 30.3403 23.0931 31.3063 22.2921 32.0579C21.8629 32.4609 21.4108 32.8388 20.9381 33.1899H20.9353C20.6648 33.3882 20.338 33.4951 20.0025 33.4951C19.6669 33.4951 19.3402 33.3882 19.0697 33.1899H19.0669C18.5941 32.8388 18.142 32.4609 17.7129 32.0579C16.9128 31.3058 15.9635 30.3403 15.3626 29.2432C14.866 28.3374 14.6067 27.3423 14.8637 26.3053C15.1103 25.3116 15.8953 24.4387 16.8582 24.3169C17.9717 24.1759 19.2683 24.9586 20.0025 25.8573C20.7366 24.9586 22.0332 24.1764 23.1467 24.3174C24.1096 24.4392 24.8946 25.3121 25.1413 26.3058C25.3982 27.3423 25.1389 28.3374 24.6424 29.2432Z"
                                  fill="#FFAA00"/>
                        </svg>

                        <h2 class="mr-3">بازیابی کلمه عبور</h2>


                    </div>
                    <div class="card p-5">
                        <form class="contact-form" method='post' action="{% url "account:forget-password" %}">
                            {% csrf_token %}
                            <div class="form-row">
                                <div class="form-group col-12">
                                    <input type="email" name="email" class="form-control mb-2"
                                           placeholder="ایمیل"
                                           value="{% if form.email.value %}{{ form.email.value }}{% endif %}">
                                    <span style="color:red">{{ form.email.errors }}</span>
                                </div>
                                <div class="form-group col-md-6 d-flex justify-content-start align-items-center">
                                    <button type="submit" class="btn btn-lightorng login-btn">ارسال لینک</button>
                                </div>
                            </div>


                        </form>
                    </div>
                </div>

                <div class="col-lg-5 d-flex align-items-center order-1 order-lg-2">
                    <img src="/static/Img/login_pic.png" class="img-fluid wapp"/>
                </div>

            </div>

        </div>
    </section>
{% endblock %}

account_module/templates/login.html
{% extends "shared/main.html" %}
{% block title %}ورود{% endblock %}


{% block content %}
    <section class="container-fluid text-lg-right text-center mt-4 p-3 mb-5">
        <div class="container">

            <div class="row d-flex align-items-center pt-lg-5">

                <div class="col-lg-7 pl-lg-5 text-center order-2 order-lg-1">
                    <div class="d-flex align-items-center mb-3">
                        <svg width="41" height="41" viewBox="0 0 41 41" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M26.2658 0.97876C28.7008 0.97876 30.6746 4.67863 30.6746 7.81348C30.6746 10.9483 28.7008 13.489 26.2658 13.489C23.8307 13.489 21.8569 10.9479 21.8569 7.81348C21.8569 4.6791 23.8307 0.97876 26.2658 0.97876Z"
                                  fill="#FFAA00"/>
                            <path d="M13.7387 0.97876C16.1737 0.97876 18.1475 4.67863 18.1475 7.81348C18.1475 10.9483 16.1737 13.489 13.7387 13.489C11.3036 13.489 9.32983 10.9479 9.32983 7.81348C9.32983 4.6791 11.3036 0.97876 13.7387 0.97876Z"
                                  fill="#FFAA00"/>
                            <path d="M0.534818 17.5109C-0.500563 14.9255 -0.0464077 11.2055 2.01777 10.3819C4.08194 9.55835 6.97583 11.9425 8.01027 14.5283C9.04471 17.1142 8.20934 19.8781 6.1447 20.7017C4.08005 21.5252 1.56879 20.0967 0.534818 17.5109Z"
                                  fill="#FFAA00"/>
                            <path d="M39.4698 17.5109C38.4344 20.0963 35.9241 21.5253 33.8599 20.7017C31.7957 19.8782 30.9604 17.1142 31.9943 14.5284C33.0283 11.9426 35.9227 9.55745 37.9868 10.3819C40.051 11.2064 40.5037 14.9251 39.4698 17.5109Z"
                                  fill="#FFAA00"/>
                            <path d="M35.776 31.7942C35.3054 29.679 34.1759 27.7667 32.9292 25.9965C30.0075 21.85 25.329 17.6627 20.0025 17.6627C14.698 17.6627 9.99787 21.8491 7.07574 25.9965C5.82905 27.7667 4.7019 29.6766 4.22892 31.7942C3.75593 33.9119 4.01478 36.2805 5.3283 37.9991C6.64182 39.7176 9.13097 40.5816 11.0756 39.649C12.2324 39.0953 13.169 37.9789 14.4448 37.8712C15.6167 37.773 16.6521 38.5608 17.6291 39.2198C18.335 39.696 19.1869 40.1294 20.0025 40.135C20.8181 40.1294 21.6694 39.696 22.3758 39.2198C23.3529 38.5617 24.3882 37.773 25.5601 37.8712C26.836 37.9789 27.7721 39.0934 28.9293 39.649C30.874 40.5816 33.3631 39.7214 34.6766 38.001C35.9902 36.2805 36.249 33.9123 35.776 31.7942ZM24.6424 29.2432C24.0414 30.3403 23.0931 31.3063 22.2921 32.0579C21.8629 32.4609 21.4108 32.8388 20.9381 33.1899H20.9353C20.6648 33.3882 20.338 33.4951 20.0025 33.4951C19.6669 33.4951 19.3402 33.3882 19.0697 33.1899H19.0669C18.5941 32.8388 18.142 32.4609 17.7129 32.0579C16.9128 31.3058 15.9635 30.3403 15.3626 29.2432C14.866 28.3374 14.6067 27.3423 14.8637 26.3053C15.1103 25.3116 15.8953 24.4387 16.8582 24.3169C17.9717 24.1759 19.2683 24.9586 20.0025 25.8573C20.7366 24.9586 22.0332 24.1764 23.1467 24.3174C24.1096 24.4392 24.8946 25.3121 25.1413 26.3058C25.3982 27.3423 25.1389 28.3374 24.6424 29.2432Z"
                                  fill="#FFAA00"/>
                        </svg>

                        <h2 class="mr-3">ورود</h2>
                    </div>
                    <div class="card p-5">
                        <form class="contact-form" method="post" action="{% url "account:login" %}">
                            {% csrf_token %}
                            <div class="form-row">
                                <div class="form-group col-12">
                                    <input type="text" name="email" class="form-control mb-2"
                                           placeholder="پست الکترونیکی"
                                           value="{% if form.email.value %}{{ form.email.value }}{% endif %}">
                                    <span style="color:red">{{ form.email.errors }}</span>
                                </div>
                                <div class="form-group col-12">
                                    <input type="password" name="password" class="form-control mb-2"
                                           placeholder="رمز عبور"
                                           value="{% if form.password.value %}{{ form.password.value }}{% endif %}">
                                    <span style="color:red">{{ form.password.errors }}</span>
                                </div>
                                <div class="form-group col-md-6 d-flex justify-content-start align-items-center">
                                    <button type="submit" class="btn btn-lightorng login-btn">ورود</button>
                                </div>
                                <div class="form-group col-md-6 d-flex justify-content-end">
                                    <a href="./sign-up.html" class="register-btn py-3 radius55">ثبت نام</a>
                                    <a href="{% url "account:forget-password" %}" class="register-btn py-3 radius55">بازیابی
                                        کلمه عبور</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

                <div class="col-lg-5 d-flex align-items-center order-1 order-lg-2">
                    <img src="/static/Img/login_pic.png" class="img-fluid wapp"/>
                </div>

            </div>

        </div>
    </section>
{% endblock %}

account_module/templates/reset-password.html
{% extends "shared/main.html" %}
{% block title %}بازیابی رمزعبور{% endblock %}



{% block content %}
    <section class="container-fluid text-lg-right text-center mt-4 p-3 mb-5">
        <div class="container">

            <div class="row d-flex align-items-center pt-lg-5">

                <div class="col-lg-7 pl-lg-5 text-center order-2 order-lg-1">
                    <div class="d-flex align-items-center mb-3">
                        <svg width="41" height="41" viewBox="0 0 41 41" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M26.2658 0.97876C28.7008 0.97876 30.6746 4.67863 30.6746 7.81348C30.6746 10.9483 28.7008 13.489 26.2658 13.489C23.8307 13.489 21.8569 10.9479 21.8569 7.81348C21.8569 4.6791 23.8307 0.97876 26.2658 0.97876Z"
                                  fill="#FFAA00"/>
                            <path d="M13.7387 0.97876C16.1737 0.97876 18.1475 4.67863 18.1475 7.81348C18.1475 10.9483 16.1737 13.489 13.7387 13.489C11.3036 13.489 9.32983 10.9479 9.32983 7.81348C9.32983 4.6791 11.3036 0.97876 13.7387 0.97876Z"
                                  fill="#FFAA00"/>
                            <path d="M0.534818 17.5109C-0.500563 14.9255 -0.0464077 11.2055 2.01777 10.3819C4.08194 9.55835 6.97583 11.9425 8.01027 14.5283C9.04471 17.1142 8.20934 19.8781 6.1447 20.7017C4.08005 21.5252 1.56879 20.0967 0.534818 17.5109Z"
                                  fill="#FFAA00"/>
                            <path d="M39.4698 17.5109C38.4344 20.0963 35.9241 21.5253 33.8599 20.7017C31.7957 19.8782 30.9604 17.1142 31.9943 14.5284C33.0283 11.9426 35.9227 9.55745 37.9868 10.3819C40.051 11.2064 40.5037 14.9251 39.4698 17.5109Z"
                                  fill="#FFAA00"/>
                            <path d="M35.776 31.7942C35.3054 29.679 34.1759 27.7667 32.9292 25.9965C30.0075 21.85 25.329 17.6627 20.0025 17.6627C14.698 17.6627 9.99787 21.8491 7.07574 25.9965C5.82905 27.7667 4.7019 29.6766 4.22892 31.7942C3.75593 33.9119 4.01478 36.2805 5.3283 37.9991C6.64182 39.7176 9.13097 40.5816 11.0756 39.649C12.2324 39.0953 13.169 37.9789 14.4448 37.8712C15.6167 37.773 16.6521 38.5608 17.6291 39.2198C18.335 39.696 19.1869 40.1294 20.0025 40.135C20.8181 40.1294 21.6694 39.696 22.3758 39.2198C23.3529 38.5617 24.3882 37.773 25.5601 37.8712C26.836 37.9789 27.7721 39.0934 28.9293 39.649C30.874 40.5816 33.3631 39.7214 34.6766 38.001C35.9902 36.2805 36.249 33.9123 35.776 31.7942ZM24.6424 29.2432C24.0414 30.3403 23.0931 31.3063 22.2921 32.0579C21.8629 32.4609 21.4108 32.8388 20.9381 33.1899H20.9353C20.6648 33.3882 20.338 33.4951 20.0025 33.4951C19.6669 33.4951 19.3402 33.3882 19.0697 33.1899H19.0669C18.5941 32.8388 18.142 32.4609 17.7129 32.0579C16.9128 31.3058 15.9635 30.3403 15.3626 29.2432C14.866 28.3374 14.6067 27.3423 14.8637 26.3053C15.1103 25.3116 15.8953 24.4387 16.8582 24.3169C17.9717 24.1759 19.2683 24.9586 20.0025 25.8573C20.7366 24.9586 22.0332 24.1764 23.1467 24.3174C24.1096 24.4392 24.8946 25.3121 25.1413 26.3058C25.3982 27.3423 25.1389 28.3374 24.6424 29.2432Z"
                                  fill="#FFAA00"/>
                        </svg>

                        <h2 class="mr-3">ایجاد رمز عبور جدید</h2>


                    </div>

                    <div class="card p-5">
                        <form class="contact-form" method='post'
                              action="{% url "account:reset-password" active_code=user.email_active_code %}">
                            {% csrf_token %}
                            <div class="form-row">
                                <div class="form-group col-12">
                                    <input type="password" name="password" class="form-control mb-2"
                                           placeholder="رمز عبور جدید"
                                           value="{% if form.pasword.value %}{{ form.password.value }}{% endif %}">
                                    <span style="color:red">{{ form.password.errors }}</span>
                                    <input type="password" name="confirm_password" class="form-control mb-2"
                                           placeholder="تکرار رمز عبور">
                                    <span style="color:red">{{ form.confirm_password.errors }}</span>
                                </div>
                                <div class="form-group col-md-6 d-flex justify-content-start align-items-center">
                                    <button type="submit" class="btn btn-lightorng login-btn">تغییر رمز عبور</button>
                                </div>
                            </div>


                        </form>
                    </div>
                </div>


                <div class="col-lg-5 d-flex align-items-center order-1 order-lg-2">
                    <img src="/static/Img/login_pic.png" class="img-fluid wapp"/>
                </div>

            </div>

        </div>
    </section>
{% endblock %}